import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:xml/xml.dart';

/// Minimal SVG renderer for the note graphics generated by the backend.
///
/// Only the small SVG subset used by the note templates is supported:
///   - root `<svg>` element with a `viewBox`
///   - `<rect>`, `<line>`, `<ellipse>` and `<path>` shapes
///   - `<g>` groups
///   - `translate`, `rotate`, `scale` and `matrix` transforms
///   - `shape-rendering="crispEdges"` (renders without antialiasing)
///
/// Unlike `flutter_svg`, antialiasing can be disabled, per element via the
/// `shape-rendering` attribute and globally via [forceAntiAlias].
class NoteSvgView extends StatelessWidget {
  const NoteSvgView({
    super.key,
    required this.svg,
    required this.height,
    this.forceAntiAlias,
  });

  final String svg;

  /// Height in logical pixels the graphic is rendered at. The width is
  /// derived from the SVG `viewBox` aspect ratio.
  final double height;

  /// When set, overrides antialiasing for every element. When null, each
  /// element decides based on its `shape-rendering` attribute.
  final bool? forceAntiAlias;

  @override
  Widget build(BuildContext context) {
    final root = _SvgParser.parse(svg);
    if (root.width == 0 || root.height == 0) {
      return const SizedBox.shrink();
    }
    final scale = height / root.height;
    return CustomPaint(
      size: Size(root.width * scale, height),
      painter: _NoteSvgPainter(root, scale, forceAntiAlias),
    );
  }
}

class _SvgRoot {
  _SvgRoot(this.minX, this.minY, this.width, this.height, this.content);

  final double minX;
  final double minY;
  final double width;
  final double height;
  final _SvgElement content;
}

class _NoteSvgPainter extends CustomPainter {
  _NoteSvgPainter(this.root, this.scale, this.forceAntiAlias);

  final _SvgRoot root;
  final double scale;
  final bool? forceAntiAlias;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.translate(-root.minX, -root.minY);
    canvas.scale(scale);
    root.content.paint(canvas, forceAntiAlias);
    canvas.restore();
  }

  @override
  bool shouldRepaint(_NoteSvgPainter oldDelegate) =>
      root != oldDelegate.root ||
      scale != oldDelegate.scale ||
      forceAntiAlias != oldDelegate.forceAntiAlias;
}

abstract class _SvgElement {
  void paint(Canvas canvas, bool? forceAntiAlias);
}

class _GroupElement extends _SvgElement {
  _GroupElement(this.transforms, this.children);

  final List<_Transform> transforms;
  final List<_SvgElement> children;

  @override
  void paint(Canvas canvas, bool? forceAntiAlias) {
    if (transforms.isEmpty) {
      for (final child in children) {
        child.paint(canvas, forceAntiAlias);
      }
      return;
    }
    canvas.save();
    for (final t in transforms) {
      t.apply(canvas);
    }
    for (final child in children) {
      child.paint(canvas, forceAntiAlias);
    }
    canvas.restore();
  }
}

class _RectElement extends _SvgElement {
  _RectElement(this.rect, this.fill, this.crisp);

  final Rect rect;
  final Color fill;
  final bool crisp;

  @override
  void paint(Canvas canvas, bool? forceAntiAlias) {
    canvas.drawRect(
      rect,
      Paint()
        ..style = PaintingStyle.fill
        ..isAntiAlias = forceAntiAlias ?? !crisp
        ..color = fill,
    );
  }
}

class _LineElement extends _SvgElement {
  _LineElement(
    this.x1,
    this.y1,
    this.x2,
    this.y2,
    this.stroke,
    this.strokeWidth,
    this.cap,
    this.crisp,
  );

  final double x1;
  final double y1;
  final double x2;
  final double y2;
  final Color stroke;
  final double strokeWidth;
  final StrokeCap cap;
  final bool crisp;

  @override
  void paint(Canvas canvas, bool? forceAntiAlias) {
    final paint = Paint()
      ..style = PaintingStyle.stroke
      ..isAntiAlias = forceAntiAlias ?? !crisp
      ..strokeWidth = strokeWidth
      ..strokeCap = cap
      ..color = stroke;
    canvas.drawLine(Offset(x1, y1), Offset(x2, y2), paint);
  }
}

class _EllipseElement extends _SvgElement {
  _EllipseElement(this.oval, this.fill, this.crisp);

  final Rect oval;
  final Color fill;
  final bool crisp;

  @override
  void paint(Canvas canvas, bool? forceAntiAlias) {
    canvas.drawOval(
      oval,
      Paint()
        ..style = PaintingStyle.fill
        ..isAntiAlias = forceAntiAlias ?? !crisp
        ..color = fill,
    );
  }
}

class _PathElement extends _SvgElement {
  _PathElement(
    this.path,
    this.fill,
    this.stroke,
    this.strokeWidth,
    this.evenOdd,
    this.crisp,
  );

  final Path path;
  final Color fill;
  final Color stroke;
  final double strokeWidth;
  final bool evenOdd;
  final bool crisp;

  @override
  void paint(Canvas canvas, bool? forceAntiAlias) {
    final antiAlias = forceAntiAlias ?? !crisp;
    path.fillType = evenOdd ? PathFillType.evenOdd : PathFillType.nonZero;
    if (fill != Colors.transparent) {
      canvas.drawPath(
        path,
        Paint()
          ..style = PaintingStyle.fill
          ..isAntiAlias = antiAlias
          ..color = fill,
      );
    }
    if (stroke != Colors.transparent && strokeWidth > 0) {
      canvas.drawPath(
        path,
        Paint()
          ..style = PaintingStyle.stroke
          ..isAntiAlias = antiAlias
          ..strokeWidth = strokeWidth
          ..color = stroke,
      );
    }
  }
}

class _Transform {
  _Transform(this.apply);

  final void Function(Canvas canvas) apply;

  static List<_Transform> parseAll(String value) {
    final transformRegex = RegExp(
      r'(translate\([^)]*\)|rotate\([^)]*\)|scale\([^)]*\)|matrix\([^)]*\))',
    );
    return [
      for (final match in transformRegex.allMatches(value))
        _Transform.parse(match.group(0)!),
    ];
  }

  static _Transform parse(String s) {
    if (s.startsWith('matrix')) {
      final numbers = _numbers(s, 'matrix');
      final a = numbers.getOr(0);
      final b = numbers.getOr(1);
      final c = numbers.getOr(2);
      final d = numbers.getOr(3);
      final e = numbers.getOr(4);
      final f = numbers.getOr(5);
      return _Transform((canvas) {
        canvas.transform(
          Float64List.fromList([
            a, b, 0, 0, //
            c, d, 0, 0, //
            0, 0, 1, 0, //
            e, f, 0, 1, //
          ]),
        );
      });
    }
    if (s.startsWith('translate')) {
      final numbers = _numbers(s, 'translate');
      return _Transform(
        (canvas) => canvas.translate(numbers.getOr(0), numbers.getOr(1)),
      );
    }
    if (s.startsWith('rotate')) {
      final numbers = _numbers(s, 'rotate');
      final angle = numbers.getOr(0);
      final cx = numbers.getOr(1);
      final cy = numbers.getOr(2);
      return _Transform((canvas) {
        if (numbers.length > 1) {
          canvas.translate(cx, cy);
          canvas.rotate(angle * math.pi / 180.0);
          canvas.translate(-cx, -cy);
        } else {
          canvas.rotate(angle * math.pi / 180.0);
        }
      });
    }
    if (s.startsWith('scale')) {
      final numbers = _numbers(s, 'scale');
      final sx = numbers.getOr(0);
      final sy = numbers.length > 1 ? numbers.getOr(1) : sx;
      return _Transform((canvas) => canvas.scale(sx, sy));
    }
    throw FormatException('Unsupported transform: $s');
  }

  static _Numbers _numbers(String s, String name) {
    final match = RegExp('$name\\(([^)]*)\\)').firstMatch(s)!;
    return _Numbers(
      match
          .group(1)!
          .trim()
          .split(RegExp(r'[\s,]+'))
          .where((part) => part.isNotEmpty)
          .map(double.parse)
          .toList(),
    );
  }
}

class _Numbers {
  _Numbers(this.values);

  final List<double> values;

  int get length => values.length;

  double getOr(int index) => index < values.length ? values[index] : 0.0;
}

class _SvgParser {
  _SvgParser(this.root);

  final XmlElement root;

  static _SvgRoot parse(String svg) {
    final document = XmlDocument.parse(svg);
    return _SvgParser(document.rootElement).build();
  }

  _SvgRoot build() {
    final viewBox = root.getAttribute('viewBox');
    double minX = 0;
    double minY = 0;
    double width;
    double height;
    if (viewBox != null) {
      final parts = viewBox.trim().split(RegExp(r'[\s,]+'));
      minX = double.parse(parts[0]);
      minY = double.parse(parts[1]);
      width = double.parse(parts[2]);
      height = double.parse(parts[3]);
    } else {
      width = _length(root.getAttribute('width'));
      height = _length(root.getAttribute('height'));
    }
    return _SvgRoot(
      minX,
      minY,
      width,
      height,
      _build(root) ?? _GroupElement(const [], const []),
    );
  }

  double _length(String? value) {
    if (value == null) return 0;
    final match = RegExp(r'^([-\d.]+)').firstMatch(value.trim());
    return match == null ? 0 : double.parse(match.group(1)!);
  }

  _SvgElement? _build(XmlElement xml) {
    if (xml.getAttribute("display") == "none") {
      return null;
    }
    _SvgElement? element;
    switch (xml.name.local) {
      case 'g':
      case 'svg':
        final children = <_SvgElement>[];
        for (final node in xml.children) {
          if (node is! XmlElement) continue;
          final child = _build(node);
          if (child != null) children.add(child);
        }
        element = _GroupElement(const [], children);
      case 'rect':
        element = _RectElement(
          Rect.fromLTWH(
            _number(xml, 'x', 0),
            _number(xml, 'y', 0),
            _number(xml, 'width', 0),
            _number(xml, 'height', 0),
          ),
          _color(xml, 'fill', Colors.transparent),
          _crisp(xml),
        );
      case 'line':
        element = _LineElement(
          _number(xml, 'x1', 0),
          _number(xml, 'y1', 0),
          _number(xml, 'x2', 0),
          _number(xml, 'y2', 0),
          _color(xml, 'stroke', Colors.transparent),
          _number(xml, 'stroke-width', 1),
          _cap(xml),
          _crisp(xml),
        );
      case 'ellipse':
        element = _EllipseElement(
          Rect.fromCenter(
            center: Offset(_number(xml, 'cx', 0), _number(xml, 'cy', 0)),
            width: 2 * _number(xml, 'rx', 0),
            height: 2 * _number(xml, 'ry', 0),
          ),
          _color(xml, 'fill', Colors.transparent),
          _crisp(xml),
        );
      case 'path':
        element = _PathElement(
          _parsePath(xml.getAttribute('d') ?? ''),
          _color(xml, 'fill', Colors.black),
          _color(xml, 'stroke', Colors.transparent),
          _number(xml, 'stroke-width', 1),
          (xml.getAttribute('fill-rule') ?? '').toLowerCase() == 'evenodd',
          _crisp(xml),
        );
      default:
        return null;
    }
    final transforms = _Transform.parseAll(xml.getAttribute('transform') ?? '');
    if (transforms.isEmpty) return element;
    return _GroupElement(transforms, [element]);
  }

  double _number(XmlElement xml, String name, double fallback) {
    final value = xml.getAttribute(name);
    if (value == null) return fallback;
    return double.parse(value.trim());
  }

  bool _crisp(XmlElement xml) => (xml.getAttribute('shape-rendering') ?? '')
      .toLowerCase()
      .contains('crisp');

  static Path _parsePath(String d) {
    final path = Path();
    final tokens = RegExp(r'[MmCcLlZz]|-?\d+(?:\.\d+)?')
        .allMatches(d)
        .map((m) => m.group(0)!)
        .toList();
    var i = 0;
    double curX = 0;
    double curY = 0;
    double startX = 0;
    double startY = 0;
    double numAt(int offset) => double.parse(tokens[i + offset]);

    while (i < tokens.length) {
      final token = tokens[i];
      if (!RegExp(r'^[MmCcLlZz]$').hasMatch(token)) {
        i++;
        continue;
      }
      i++;
      switch (token) {
        case 'M':
        case 'm':
          if (token == 'M') {
            curX = numAt(0);
            curY = numAt(1);
          } else {
            curX += numAt(0);
            curY += numAt(1);
          }
          path.moveTo(curX, curY);
          startX = curX;
          startY = curY;
          i += 2;
        case 'L':
        case 'l':
          if (token == 'L') {
            curX = numAt(0);
            curY = numAt(1);
          } else {
            curX += numAt(0);
            curY += numAt(1);
          }
          path.lineTo(curX, curY);
          i += 2;
        case 'C':
        case 'c':
          if (token == 'C') {
            path.cubicTo(numAt(0), numAt(1), numAt(2), numAt(3), numAt(4), numAt(5));
            curX = numAt(4);
            curY = numAt(5);
          } else {
            path.cubicTo(
              curX + numAt(0),
              curY + numAt(1),
              curX + numAt(2),
              curY + numAt(3),
              curX + numAt(4),
              curY + numAt(5),
            );
            curX += numAt(4);
            curY += numAt(5);
          }
          i += 6;
        case 'Z':
        case 'z':
          path.close();
          curX = startX;
          curY = startY;
      }
    }
    return path;
  }

  Color _color(XmlElement xml, String name, Color fallback) {
    final value = xml.getAttribute(name);
    if (value == null || value.trim() == 'none') return fallback;
    final color = value.trim();
    if (color.startsWith('#')) {
      var hex = color.substring(1);
      if (hex.length == 3) {
        hex = hex.split('').map((c) => '$c$c').join();
      }
      if (hex.length == 6) hex = 'ff$hex';
      return Color(int.parse(hex, radix: 16));
    }
    switch (color.toLowerCase()) {
      case 'black':
        return Colors.black;
      case 'white':
        return Colors.white;
      case 'transparent':
        return Colors.transparent;
      default:
        return fallback;
    }
  }

  StrokeCap _cap(XmlElement xml) {
    switch (xml.getAttribute('stroke-linecap')) {
      case 'round':
        return StrokeCap.round;
      case 'square':
        return StrokeCap.square;
      default:
        return StrokeCap.butt;
    }
  }
}
